### ISSUE TITLE
Possibility to autogenerate concrete objects

### ISSUE THREAD

**Issue by zrajnai** [michal-ciechan/Moqqer#17]
Thanks for this very useful tool!

Is it possible to add the ability to optionally create Objects automatically when they're encountered in constructor parameters?
Like creating the complete tree on-the-fly without having to specify Use for every concrete type in advance? (something like automatically doing moqqer.Use<T>(moqqer.Create<T>...)  recursively.

Furthermore, it would be nice to specify whether to reuse the single instance of created objects/mocks, or specify a Func<T> to be able to create several instances.

Thanks!

**Comment by michal-ciechan** [comment]
Thanks for your feedback.

And yeah definitely will add those.

The auto generation will add this weekend as a property on Moqqer. So

moqqer = new Moqqer
{
    ConcreteObjectGeneration = true,
}

The reason I left it out is because it generally is a code smell if I depend on an object that does not have a default ctor and needs other dependencies. But if it will be useful to you then I will add it as a setting.

The Func creation will be a little more involved. But will add separate issue and work on it this weekend. But can't promise I will do finish it this weekend!

Thinking of something like

_moq.Factory<ISomeInterface>(context => context.Default);

Ofcourse you will be able to add custom logic in there to either create a new instance or use the singleton.

Will add the following properties to context:

Type Caller { get; }
MethodInfo Method { get; }
Object[] Args { get; }

Would those be sufficient?

Get Outlook for Android<https://aka.ms/ghei36>



From: Zoltan Rajnai
Sent: Friday, 12 May, 09:03
Subject: [michal-ciechan/Moqqer] Possibility to autogenerate ojects (#17)
To: michal-ciechan/Moqqer
Cc: Subscribed


Thanks for this very useful tool!

Is it possible to add the ability to optionally create Objects automatically when they're encountered in constructor parameters?
Like creating the complete tree on-the-fly without having to specify Use for every concrete type in advance? (something like automatically doing moqqer.Use(moqqer.Create...) recursively.

Furthermore, it would be nice to specify whether to reuse the single instance of created objects/mocks, or specify a Func to be able to create several instances.

Thanks!

**Comment by zrajnai** [comment]
I have the recursive generation implemented with a parameter on Create..
I will issue a Pull request in a couple of minutes :)

I like your Factory idea!
